gsheet_id = "1fMk74h7dTuKz2QjYY9guMPeOeBxQPrWRDtqWfoA87wA"

[gcp_service_account]
type = "service_account"
project_id = "kost-management-466414"
private_key_id = "a37a94bcd0b85e24df0f6738dd97307e78e642d6"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCx2CUodo0+18Nq
1ZUo5qOUOrbt7c2apMvMXMt9QVvsbxirwHCNquE7lTU/2wmRjsKma6tsdVus7c2Q
TOB7S7vL+SndgV2ykqULIbeTD7BjtgynN7rDzstpJe3jxNK14NFWZx90DbtOK8vY
4R8DDBJmt9ZOjuNciHItwLcbqCZoLPRl+34LdkyzadvOxD3cHDwjm0G1SrX8uxl+
v3Wgraejzo6nff66r8c+arhoAvU7PIhD07Eutg4eQtEDBJ941bjp3VsdU87thkhc
yEpmD3j2CJ+VnBznW2oDTyUkGVjcfI0rHfWIA1sE1NMRdjrwXsuZlKlDvJILYOZJ
APIX98UFAgMBAAECggEACkOt3Vh+TXa5hiR+n+Yz4b3Dyha0C61gP9LJQdjwW8SL
uXn5ZQvMRRqXALD9K+P/8wf61F8vo9rzxtTRDfywgZTHaEvrov9YvDw9cqTwqsia
kVojkuKQFekFAmTdPncTzfdUtueF/HyFnuZbWlsrgrcwjMctcy1C3cYmK1f4o4F/
1L/CkMCxfNvxyCxqb/+Ktf1IRrfQyS7ERe6GwlHjTYAzlTH9VV6FiJDNex+onAUF
IvGJdnibpjxTCQpNlVeHEecFZnMnDMFRqklH3ert4ECUM3eoOJ3/21ecsdF1krr9
2Bgy0ju5f534YyiS05rhIenfOOAdMnhbON9BZ+iHDwKBgQD2a9tE34zpzdukQjDi
he0kkSusDHBU86Fd8gcVrbH3ewkYAaC3cPpAhi8lPn8XR/Ip+yCeFaoiq9FWcMYj
kzGbW1GlZaG4KGtZTB6czhAAxEbJoU/QQeSX77MnJoNheGRTZ0FMOwSeQRMEMoB8
vU9mX0twJa06KD+DuWmIoRG+3wKBgQC4weCmggRf2Pi8Za4VOdPPsZG2FA1XhtAQ
2NcOCGTaziW7lksFEo9CfgFMk6lykFVbElc0iADYioFdgwbpBXogPCOY6/DuEQ0Z
Qaq3ftWw5eQNHEXSvGSMenONANud1l48VMMeJ7NCI5gd6Z9IWzbe5YzcNbD+CUO4
Onw4N1FMmwKBgQDUEsrooUQSy7nlyZlsujn3KIDfVu0uD2anBW6Xd58cD+Uppez9
MtwMv+6/LOQP0zlUa+4MXzTHFfvZWsELSNh+jb7ci3T8mryYY2xNIwKexkztpkic
QLlNEVurq/eR4Rzmsox94KT+1Z5aFGSD9iDpR8YSxDorPQw8f0uV7JjrHQKBgEGU
2EhieGkJXGmLcjqoly3vKvjFr2K1QN/qCJQ7mIkuiahHlgOL7fw9O/rRo2E+KH42
SWwlJp+2smreGrLWNd6BWmVqws/Oj6a6b33I8NNlFwksUwCVzN8sjB2uA0bIlBS4
RbZLg07j0Zg0mEyXzCdcth5olJXn9fjMEdHmmN4nAoGAHgQgzfXuvR2kGcZ2ho5P
8eHFKdqMYQZN6OBwtTZb7FHU3bwkidfISgkGvD1E2J8gISvkmr29w5CkLQMKp0Iw
5hjqRJYPdqyUNawE5R/S4O8ZjHufWRYlTpTAVYUjl0nb15JEQefqc5WXbVfpxPCp
hiGaitWl1CaVkq2IiPTW4e4=
-----END PRIVATE KEY-----"""
client_email = "streamlit-kost-access@kost-management-466414.iam.gserviceaccount.com"
client_id = "106536013481306394186"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-kost-access%40kost-management-466414.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
